notebook/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds

end

notebook/app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact

  validates :street, :city, :state, presence: true 
end

notebook/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :kind
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy 
  
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :nome, presence: true, length: { minimum: 3 }
  validates :email, presence: true
end

notebook/app/models/kind.rb
class Kind < ActiveRecord::Base
	has_many :contacts

	validates :description, presence: true
end

notebook/app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :phone,  presence: true 
end

notebook/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

notebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

notebook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_kind_select, only: [:new, :edit, :update, :create]
  before_action :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:nome).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t("mensages.created") }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t("mensages.updated") }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('mensages.destroyed') }
      format.json { head :no_content }
    end
  end

  private

    def set_kind_select
      @kind_select_all = Kind.order(:description)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nome, :email, :kind_id, :rmk,
                                        address_attributes: [:street, :city, :state],
                                        phones_attributes:[:id, :phone, :_destroy])
    end
end

notebook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

notebook/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #http_basic_authenticate_with name: "admin", password: "Helpoiu098", except: [:index, :show]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.order(:description).page(params[:page]).per(15)
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: I18n.t("mensages.created") }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: I18n.t("mensages.updated") }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_path, notice: I18n.t("mensages.destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

notebook/app/helpers/addresses_helper.rb
module AddressesHelper
end

notebook/app/helpers/application_helper.rb
module ApplicationHelper

	ESTADOS_BRASILEIROS = [
	    ["Acre", "AC"],
	    ["Alagoas", "AL"],
	    ["Amapá", "AP"],
	    ["Amazonas", "AM"],
	    ["Bahia", "BA"],
	    ["Ceará", "CE"],
	    ["Distrito Federal", "DF"],
	    ["Espírito Santo", "ES"],
	    ["Goiás", "GO"],
	    ["Maranhão", "MA"],
	    ["Mato Grosso", "MT"],
	    ["Mato Grosso do Sul", "MS"],
	    ["Minas Gerais", "MG"],
	    ["Pará", "PA"],
	    ["Paraíba", "PB"],
	    ["Paraná", "PR"],
	    ["Pernambuco", "PE"],
	    ["Piauí", "PI"],
	    ["Rio de Janeiro", "RJ"],
	    ["Rio Grande do Norte", "RN"],
	    ["Rio Grande do Sul", "RS"],
	    ["Rondônia", "RO"],
	    ["Roraima", "RR"],
	    ["Santa Catarina", "SC"],
	    ["São Paulo", "SP"],
	    ["Sergipe", "SE"],
	    ["Tocantins", "TO"]
  	]

	def options_for_state(select)
		options_for_select(ESTADOS_BRASILEIROS, select)
	end
end

notebook/app/helpers/contacts_helper.rb
module ContactsHelper
end

notebook/app/helpers/home_helper.rb
module HomeHelper
end

notebook/app/helpers/kinds_helper.rb
module KindsHelper
end

notebook/app/helpers/phones_helper.rb
module PhonesHelper
end

notebook/app/views/contacts/_form.html.erb
<br>
<%= form_for(@contact, html: { class: "basic-grey" }) do |f| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@contact.errors.count, t('mensages.errors'))}" %></h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1><%= "Contacts" %></h1>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= collection_select(:contact, :kind_id, @kind_select_all, :id, :description) %>
  </div>
 
 <%= f.fields_for :address do |address_field| %>
    <div class="field">
      <%= address_field.label :street %><br>
      <%= address_field.text_field :street %>
    </div>
    <div class="field">
      <%= address_field.label :city %><br>
      <%= address_field.text_field :city %>
    </div>
    <div class="field">
      <%= address_field.label :state %><br>
      <%= address_field.select :state, options_for_state(@contact.address.state) %>
    </div>
  <% end %>
  
  <div id="phones">
    <%= f.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>
    
    
    <div class="field">
      <%= f.label :phones, "<span class='glyphicon glyphicon-phone-alt' aria-hidden='true'></span>".html_safe %><br>
      <%= link_to_add_association("[+]", f, :phones, class: "btn btn-primary") %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk %>
  </div>
  <div align="center" class="actions">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
    <%= link_to "Voltar", contacts_path, class: "btn btn-danger" %>
    <%= link_to "Home", root_path, class: "btn btn-success" %>
  </div>
  
<% end %>

notebook/app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone, class: "phone-field" %>
		<%= link_to_remove_association('remover', f, class: "btn btn-danger") %>
	</div>
</div>

notebook/app/views/contacts/edit.html.erb
<%= render 'form' %>

notebook/app/views/contacts/index.html.erb
<div class="table-responsive">
  
  <script type="text/javascript">
    $.notify("<%= notice %>", "success");
  </script>
  
  <h1><%= "#{t("mensages.list")} de #{@contacts.model_name.human(count: @contacts.size)}" %></h1>

  <table class="table">
    <thead>
      <tr>
        <th><%= Contact.human_attribute_name("nome") %></th>
        <th><%= Contact.human_attribute_name("email") %></th>
        <th><%= Contact.human_attribute_name("kind") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background: <%= cycle("white", "#F7F7F7") %>">
          <td><%= contact.nome %></td>
          <td><%= contact.email %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t("buttons.edit"), edit_contact_path(contact) %></td>
          <td><%= link_to t("buttons.destroy"), contact, method: :delete, data: { confirm: t("mensages.confirm") } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @contacts %>
  <br>

  <%= link_to "Novo Contato", new_contact_path, class: "btn btn-primary" %>
  <%= link_to "Home", root_path, class: "btn btn-success" %>
</div>

notebook/app/views/contacts/show.html.erb
<%= form_for(@contact, html: { class: "basic-grey" }) do |f| %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong><%= Contact.human_attribute_name("nome") %>:</strong>
	  <%= @contact.nome %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @contact.email %>
	</p>

	<p>
	  <strong>Kind:</strong>
	  <%= @contact.kind.description %>
	</p>

	<p>
	  <strong><%= Contact.human_attribute_name("rmk") %>:</strong>
	  <%= @contact.rmk %>
	</p>

	<%= link_to "Edit", edit_contact_path(@contact), class: "button" %> |
	<%= link_to "Voltar", contacts_path, class: "button" %>
<% end %>

notebook/app/views/home/index.html.erb
<br>
<div class="basic-grey">
	<h1>Seja bem vindo!</h1>
	<% if user_signed_in? %>
		<%= current_user.email %>
		<p><ul>
		<li><span class="glyphicon glyphicon-tags" aria-hidden="true"></span> <%= link_to "Tipos", kinds_path %></li>
		<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= link_to "Contato", contacts_path %></li>
		</ul></p>
		<%= link_to "Sair", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Login",  new_user_session_path%>
		<%= link_to "Cadastrar",  new_user_registration_path%>
	<% end %>
</div>

notebook/app/views/kinds/_form.html.erb
<br>
<%= form_for(@kind, html: { class: "basic-grey" }) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Tipos</h1>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions" class="actions">
    <%= f.submit 'Salvar', class: "btn btn-primary" %>
    <%= link_to 'Voltar', kinds_path, class: "btn btn-danger" %>
    <%= link_to 'Home', root_path, class: "btn btn-success" %>
  </div>
<% end %>

notebook/app/views/kinds/edit.html.erb
<%= render 'form' %>

notebook/app/views/kinds/index.html.erb
<div class="table-responsive">
  
  <script type="text/javascript">
    $.notify("<%= notice %>", "success");
  </script>

  <h1>Listing Kinds</h1>

  <table class="table">
    <thead>
      <tr>
        <th><%= Kind.human_attribute_name("description") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr style="background: <%= cycle('white', '#F7F7F7') %>">
          <td><%= kind.description %></td>
          <td><%= link_to t("buttons.edit"), edit_kind_path(kind) %></td>
          <td><%= link_to t("buttons.destroy"), kind, method: :delete, data: { confirm: t('mensages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
    <%= paginate @kinds %>
  <br>

  <%= link_to 'Novo Tipo', new_kind_path, class: "btn btn-primary" %>
  <%= link_to 'Home', root_path, class: "btn btn-success" %>
</div>

notebook/app/views/kinds/new.html.erb
<%= render 'form' %>

notebook/app/views/kinds/show.html.erb
<%= form_for(@kind, html: { class: "basic-grey" }) do |f| %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Description:</strong>
	  <%= @kind.description %>
	</p>
	<%= link_to 'Edit', edit_kind_path(@kind), class: "button" %> |
	<%= link_to 'Voltar', kinds_path, class: "button" %>
<% end %>

notebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <%= stylesheet_link_tag    'application' %>
  <%= stylesheet_link_tag    params[:controller] %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag params[:controller] %>
  <%#= javascript_include_tag 'alert' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

notebook/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>